name: Testing

on: [push, pull_request]

jobs:
  test:
    name: Test on .NET Core
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Use .NET 3.1.102
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102

      - name: Building
        run: |
          dotnet build MathCore.NET/MathCore.NET.csproj --nologo          
          dotnet build Tests/MathCore.NET.Tests/MathCore.NET.Tests.csproj --nologo
          
      - name: Run Tests
        run: dotnet test Tests/MathCore.NET.Tests/MathCore.NET.Tests.csproj --nologo
